M48
; DRILL file {KiCad 9.0.6} date 2026-08-20T21:13:16+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-20T21:13:16+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X16.0Y-24.0
X16.0Y-113.25
X116.2Y-24.0
X146.0Y-113.25
M30
